AWSTemplateFormatVersion: '2010-09-09'
Description: Template para IAM (Politica y Rol) - Replicacion S3
Metadata:
  Author: Brayan Neciosup
  Proyecto: Replicacion S3 - MultiRegion

Parameters:
  
  BucketNameOrigenParameter:
    Type: String
    Default: bucket-brayan-origen-replicacion-cf
  
  BucketNameDestinoParameter:
    Type: String
    Default: bucket-brayan-destino-replicacion-cf
  
  ManagedPolicyNameParameter:
    Type: String
    Description: Nombre de la politica IAM personalizada para replicacion S3
    Default: PoliticaPersonalizada-ReplicacionS3-CF
  
  RoleNameParameter:
    Type: String
    Description: Nombre del rol IAM personalizado para replicacion S3
    Default: RolPersonalizado-ReplicacionS3-CF

Resources:
  PoliticaPersonalizadaReplicacionS3:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Sid: Regla1BucketOrigen
            Effect: Allow
            Action:
              - s3:GetReplicationConfiguration
              - s3:ListBucket
            Resource: !Sub arn:aws:s3:::${BucketNameOrigenParameter}

          - Sid: Regla2BucketOrigen
            Effect: Allow
            Action:
              - s3:GetObjectVersionForReplication
              - s3:GetObjectVersionAcl
              - s3:GetObjectVersionTagging
            Resource: !Sub arn:aws:s3:::${BucketNameOrigenParameter}/*

          - Sid: Regla1BucketDestino
            Effect: Allow
            Action:
              - s3:ReplicateObject
              - s3:ReplicateDelete
              - s3:ReplicateTags
            Resource: !Sub arn:aws:s3:::${BucketNameDestinoParameter}/*
      ManagedPolicyName: !Ref ManagedPolicyNameParameter

  RolReplicacionS3Cloudformation:
    Type: AWS::IAM::Role
    DependsOn: PoliticaPersonalizadaReplicacionS3
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sts:AssumeRole
      Description: Rol para S3 - Replicacion MultiRegion
      ManagedPolicyArns: 
        - !Ref PoliticaPersonalizadaReplicacionS3  
      MaxSessionDuration: 3600
      Path: /
      RoleName: !Ref RoleNameParameter

Outputs:
  RoleName:
    Value: !GetAtt RolReplicacionS3Cloudformation.Arn
    Export:
      Name: RoleArnExport
  

