AWSTemplateFormatVersion: '2010-09-09'
Description: Template para crear Internet Gateway para las subredes publicas
Metadata:
  Author: Brayan Neciosup
  Proyecto: Redes en AWS

Parameters:
  InternetGatewayNameParameter:
    Type: String
    Description: Nombre del Internet Gateway
    Default: IGW-Brayan-CF

Resources:
  InternetGatewayResource: ## RECURSO DE INTERNET GATEWAY
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags: 
        - Key: Name
          Value: !Ref InternetGatewayNameParameter

  AttachVPCInternetGatewayResource: ## RECURSO PARA ASOCIAR INTERNET GATEWAY A LA VPC
    Type: AWS::EC2::VPCGatewayAttachment
    DependsOn: InternetGatewayResource
    Properties:
      InternetGatewayId: !Ref InternetGatewayResource
      VpcId: !ImportValue VPCidExport ## IMPORTAR VPC ID DEL STACK

Outputs:
  InternetGatewayId:
    Value: !Ref InternetGatewayResource 
    Export:
      Name: InternetGatewayIdExport ## EXPORTAMOS EL ID DEL INTERNET GATEWAY
